permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Coffee Diary
title: Mug
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, mug, free, download, SEO, blog, web"
# url: http://nandomoreira.me
# domain_name: nandomoreira.me
# google_analytics: UA-52446115-1
repo: https://github.com/pxlu/coffee-diary
disqus_shortname: "pxlu"
author: pxlu

social:
  github    : https://github.com/pxlu

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
